name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cacheName: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cacheName }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install and Test
        run: |
          yarn
          yarn test
        env:
          CI: true

  build:
     needs: install-and-test
     runs-on: ubuntu-latest
     outputs:
        cache-hit: ${{ steps.cache.outputs.cache-hit }}
     steps:
       - name: Checkout
         uses: actions/checkout@master
       - name: Cache node modules
         uses: actions/cache@v2
         env:
           cache-name: cache-node-modules
         with:
           path: '**/node_modules'
           key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
       - name: Build
         run: yarn build
       - id: cache
         uses: actions/cache@v2
         env:
           cache-name: cache-build
         with:
           path: '**/build'
           key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/build') }}
  deploy:
     runs-on: ubuntu-latest
     needs: build
     if: ${{!needs.build.outputs.cache-hit}}
     steps:
       - name: Cache build
         uses: actions/cache@v2
         env:
           cache-name: cache-build
         with:
           path: '**/build'
           key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/build') }}
       - name: Copy build files via ssh
         uses: appleboy/scp-action@edc8ec9139a2687bcebf0249d0352ff2a988df00
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           port: ${{ secrets.PORT }}
           passphrase: ${{ secrets.PASSPHRASE }}
           key: ${{ secrets.KEY }}
           source: build
           target: /var/www/juliusrasimas
